#Introdução ao NumPy


---


[documentação](https://numpy.org/doc/stable/index.html)



---



>[Introdução ao NumPy](#scrollTo=Z2Ur5SspUJlO)

>>[1. vamos começar por importar a biblioteca](#scrollTo=ZxiRWYNLgXq-)

>>[2. vamos criar um array de uma dimensão (1D) usando uma lista](#scrollTo=_o03LNFpg4li)

>>[3. vamos agora criar um array 2D](#scrollTo=WCMytX22iGbd)

>>[4. Qual a razão de utilizar NumPy arrays, quando podíamos usar listas?](#scrollTo=_4BWcPvKj3Sg)

>>[5.  Vamos ver outras funções da biblioteca](#scrollTo=4DVNUOAW8nNk)

>>[6. Vamos agora criar um array 3D](#scrollTo=0KNxsZldV1Vv)

>>[7. Vamos agora utilizar as funções](#scrollTo=jLwnrNFEV_-X)



## 1.&nbsp;vamos começar por importar a biblioteca

In [2]:
import numpy as np

## 2.&nbsp;vamos criar um array de uma dimensão (1D) usando uma lista

In [3]:
# elemento lista do python
python_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# elemento array 1D
array_1D = np.array(python_list)

# vamos ver as duas variáveis
print(python_list)
print(array_1D)

# vamos ver os tipos das variáveis
print(type(python_list))
print(type(array_1D))
print(array_1D.shape)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
<class 'list'>
<class 'numpy.ndarray'>
(10,)


##3.&nbsp;vamos agora criar um array 2D
Para isso usamos uma lista de listas <br>
Um array 3D é criado com uma lista de listas de listas





In [3]:
# lista de listas
python_list_of_lists = [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]

# array 2D
array_2D = np.array(python_list_of_lists)

# vamos ver a variável e o seu tipo
print(array_2D)
print(type(array_2D))
print(array_2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


##4.&nbsp;Qual a razão de utilizar NumPy arrays, quando podíamos usar listas?
Enquanto que uma lista aceita diferentes tipos de dados, um NumPy array apenas aceita o mesmo tipo de dados em todos os elementos

In [7]:
# lista com diferentes tipos de dados
python_list_2 = ["teste", False, 3567, 0.567, [1,2,3]]

print(python_list_2)
# NumPy array
boolean_array = np.array([[True, False], [False, False], [False, True]])
print(boolean_array)
print(boolean_array.shape)
float_array = np.array([2.5, 4.3, 6.7])
print(float_array)
print(float_array.shape)

['teste', False, 3567, 0.567, [1, 2, 3]]
[[ True False]
 [False False]
 [False  True]]
(3, 2)
[2.5 4.3 6.7]
(3,)


##5.&nbsp; Vamos ver outras funções da biblioteca

In [13]:
# array de zeros
array_of_zeros = np.zeros((2,2,3)) # tuple
print(array_of_zeros)

#array de uns
array_of_ones = np.ones((2,2,3)) # tuple
print(array_of_ones)

# array de números aleatórios entre 0 e 1
array_of_random_numbers = np.random.random((2,10)) # tuple
print(array_of_random_numbers)

# array de números inteiros
array_of_random_int_numbers = np.random.randint(5, size=(2, 4)) # (min,max,size)
print(array_of_random_int_numbers)

# array de inicialização
initialisation_array = np.empty((2,2)) #tuple
print(initialisation_array)

# array sequência
sequence_array = np.arange(1,3,0.5) # (min,max,size)
print(sequence_array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[0.78047053 0.39733618 0.85138333 0.99462329 0.8980728  0.0136752
  0.18557809 0.72209041 0.66439556 0.18554341]
 [0.16471183 0.18671565 0.10944081 0.06962611 0.35383938 0.20591061
  0.7434036  0.09799072 0.03972904 0.78128549]]
[[3 1 1 3]
 [2 0 0 2]]
[[6.36598737e-314 6.36598737e-314]
 [4.24399158e-314 4.24399158e-314]]
[1.  1.5 2.  2.5]


##6.&nbsp;Vamos agora criar um array 3D
Para isso usamos uma lista de listas de listas <br>

In [18]:
# 2 arrays 2D
array_1_2D = np.array([[1, 2], [3, 4]])
array_2_2D = np.array([[5, 6], [7, 8]])

print(array_2_2D.shape)
# array 3D
array_3D = np.array([array_1_2D, array_2_2D])
print(array_3D)

print(array_3D.shape)

# vamos ver os tipos das variáveis
print(type(array_3D))
print(array_3D.shape)

(2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
<class 'numpy.ndarray'>
(2, 2, 2)


##7.&nbsp;Vamos agora utilizar as funções
*  flatten
*  reshape


In [23]:
# vamos olhar outra vez para o array 2D
print(array_2D)

# vamos "achatar" o array para um array 1D
array_2D_to_1D = array_2D.flatten()
print(array_2D_to_1D)

# exemplos de reshape
ex_1 = (2,4)
ex_2 = (4,2)
ex_3 = (2,3)

print(array_3D)
array_3D_to_2D = array_3D.reshape(ex_2)
print(array_3D_to_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
