#Introdução ao NumPy (parte 2)


---


[documentação](https://numpy.org/doc/stable/index.html)



---



>[Introdução ao NumPy](#scrollTo=Z2Ur5SspUJlO)

>>[1. Vamos começar por importar a biblioteca](#scrollTo=ZxiRWYNLgXq-)

>>[2. Vamos indexar](#scrollTo=_o03LNFpg4li)

>>[3. Vamos agora retirar fatias de informação](#scrollTo=P7m2ZOp7aSw-)

>>[4. Vamos ordenar arrays](#scrollTo=Kl0iWS26TuOG)

>>[5. Vamos filtrar arrays](#scrollTo=2y0F4sUjeOf5)

>>[6. Concatenar](#scrollTo=1YbQb5yumXAg)

>>[7. Delete](#scrollTo=MwhNwbyfi0B4)



## 1.&nbsp;Vamos começar por importar a biblioteca

In [2]:
import numpy as np

## 2.&nbsp;Vamos indexar

In [3]:
# indexar um array 1D
array_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7])
array_1D
array_1D[0]

#indexar um array 2D
array_2D = np.arange(24).reshape(6,4)
array_2D
array_2D[1, 1]
array_2D[0]
array_2D[:,0]
array_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 3.&nbsp;Vamos agora retirar fatias de informação <br>
(slice)

In [12]:
# queremos os primeiros 3 números do array 1D
array_1D[0:3]

# queremos apenas os números ímpares do array 1D
array_1D[1::2]

# queremos apenas o quadrado interno do array 2D
array_2D[1:5, 1:3]

# queremos os quatro cantos do array 2D
array_2D[0::5,0::3]

array([[ 0,  3],
       [20, 23]])

In [15]:
array_2D[1:5, 1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

##4.&nbsp;Vamos ordenar arrays

In [16]:
# queremos ordenar um array 1D
new_array_1D = [1, 4, 2, 5, 7, 3, 5, 1, 8, 3]
new_array_1D_sort = np.sort(new_array_1D)
print(new_array_1D_sort)

[1 1 2 3 3 4 5 5 7 8]


In [17]:
# queremos agora fazer o mesmo para um array 2D
new_array_2D = [[1, 4, 2], [6, 5, 1]]
new_array_2D_sort = np.sort(new_array_2D)
new_array_2D_sort
new_array_2D_sort = np.sort(new_array_2D, axis = 0)
new_array_2D_sort

array([[1, 4, 1],
       [6, 5, 2]])

##5.&nbsp;Vamos filtrar arrays
*   Masks -> entrega o valor
*   np.where() -> entrega o índice



In [21]:
# criar um array 1D
odd_numbers = np.arange(1,10,2)
odd_numbers

# vamos criar uma máscara de booleanos
odd_numbers >= 5
mask = odd_numbers >= 5

#filtramos o array 1D de acordo com a condição
odd_numbers[mask]

# situação com array 2D
# exemplo de um array com o número das salas e a sua dimensão
room_ids_and_sizes = np.array([[1, 12],
                               [2, 15],
                               [3, 17],
                               [4, 11],
                               [5, 25]])

# quais as salas com pelo menos 15 m2?
# vamos criar uma máscara de booleanos
room_ids_and_sizes [:,1] >= 15
mask_id = room_ids_and_sizes [:,1] >= 15

# filtramos o array 2D de acordo com a condição
room_ids_and_sizes[mask_id,0]

# usemos agora o np.where
np.where(room_ids_and_sizes[:,1] >= 15)

# podemos sempre querer as posições das linhas e das colunas
np.where(room_ids_and_sizes >3)
rows_id, cols_id = np.where(room_ids_and_sizes >3)
rows_id
cols_id

# podemos usar np.where para substituir dados no array
np.where(room_ids_and_sizes > 3, 0, room_ids_and_sizes)

array([[1, 0],
       [2, 0],
       [3, 0],
       [0, 0],
       [0, 0]])

##6.&nbsp;Concatenar

In [36]:
# temos mais duas salas para juntar ao array
new_ids_and_sizes = np.array([[6, 30],[7, 12]])
new_ids_and_sizes

# vamos então concatenar
np.concatenate((room_ids_and_sizes,new_ids_and_sizes)) # axis = 0

# mas e se agora tivermos os valores para o comprimento e a largura das salas?
new_room_characteristics = np.array([[6, 2],[5, 3], [4, 17/4], [3, 11/3], [5, 5]])
new_room_characteristics

#vamos concatenar
np.concatenate((room_ids_and_sizes, new_room_characteristics))

# temos de definir o eixo (por default, np.concatenate considera axis = 0)
np.concatenate((room_ids_and_sizes, new_room_characteristics), axis = 1)

array([[ 1.        , 12.        ,  6.        ,  2.        ],
       [ 2.        , 15.        ,  5.        ,  3.        ],
       [ 3.        , 17.        ,  4.        ,  4.25      ],
       [ 4.        , 11.        ,  3.        ,  3.66666667],
       [ 5.        , 25.        ,  5.        ,  5.        ]])

In [41]:
#vamos concatenar
np.concatenate((room_ids_and_sizes, new_room_characteristics), axis = 1)

array([[ 1.        , 12.        ,  6.        ,  2.        ],
       [ 2.        , 15.        ,  5.        ,  3.        ],
       [ 3.        , 17.        ,  4.        ,  4.25      ],
       [ 4.        , 11.        ,  3.        ,  3.66666667],
       [ 5.        , 25.        ,  5.        ,  5.        ]])

##7.&nbsp;Delete

In [42]:
# vamos adicionar as dimensões às salas
room_ids_sizes_characteristics = np.concatenate((room_ids_and_sizes,
                                                 new_room_characteristics),
                                                axis = 1)
room_ids_sizes_characteristics

# vamos remover a coluna da largura (a área e o comprimento são suficientes)
np.delete(room_ids_sizes_characteristics, 3, axis = 1)

# vamos remover a sala de 11 m2
np.delete(room_ids_sizes_characteristics, 3, axis = 0)

# e se faltar o axis?
np.delete(room_ids_sizes_characteristics, 3)
# remove o elemento na quarta posição, considerando o array flatten!



array([ 1.        , 12.        ,  6.        ,  2.        , 15.        ,
        5.        ,  3.        ,  3.        , 17.        ,  4.        ,
        4.25      ,  4.        , 11.        ,  3.        ,  3.66666667,
        5.        , 25.        ,  5.        ,  5.        ])