# Vamos aplicar o que aprendemos sobre os Numpy array


*   Complete com o código em falta
*   Sempre que necessário, **substitua** ___



Corra a primeira célula de código para obter o array com que vamos trabalhar

In [1]:
import numpy as np

# array com # camas e # de beliches existentes
# dados do grupo "urbRes", uma empresa de hostels
# significado das colunas:
  # - id do quarto
  # - # de camas
  # - # de beliches
np.random.seed(1234)
number_of_rows = 100
room_ids = np.random.choice(np.arange(1000001, 1000020), number_of_rows)
room_ids_sorted = np.sort(room_ids)
number_of_beds = np.random.choice(np.arange(1, 9), number_of_rows)
number_of_bunk_beds = np.where(number_of_beds > 3, number_of_beds, 0)
number_of_beds = np.where(number_of_beds > 3, 0, number_of_beds)

bedrooms_ids = np.stack([room_ids_sorted, number_of_beds, number_of_bunk_beds],
                        axis=1)

In [3]:
# array a utilizar
bedrooms_ids

# selecione todas as linhas da coluna 1 (queremos os ids dos quartos)
room_ids_only = bedrooms_ids[:,0]

# faça print dos primeiros 5 ids
print(room_ids_only[:5])

# recolha o id do décimo quarto usando o room_ids_only
tenth_room_id = room_ids_only[9]
print(tenth_room_id)

# recolha a fatia dos cinco ids a contar do décimo quarto usando o room_ids_only
rooms_ids_slice = room_ids_only[9:14]
print(rooms_ids_slice)

# crie um array com os primeiros 20 números de camas usando o bedrooms_ids
first_twenty_bedroom_beds = bedrooms_ids[:20,1]
print(first_twenty_bedroom_beds)

# crie um array com os números de camas dos indices pares desde 20 a 40 usando o bedrooms_ids
every_other_bedroom_beds = bedrooms_ids[20:41:2,1]
print(every_other_bedroom_beds)

# recolha a informação do número de camas e ordene-a do mais pequeno para o maior
sorted_bedroom_beds = np.sort(bedrooms_ids[:,1])
print(sorted_bedroom_beds)

[1000001 1000001 1000001 1000001 1000001]
1000003
[1000003 1000003 1000003 1000003 1000003]
[0 1 0 1 0 2 1 0 2 0 1 3 1 0 3 3 0 0 0 3]
[2 0 2 3 0 0 3 0 2 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]


In [4]:
# um dos quartos tinha um erro (tinha 8 camas em vez de 3)
bedrooms_ids[11,1] = 8

# crie um array que contenha a linha dos dados completa relativa ao quarto com o erro
bedroom_error = bedrooms_ids[bedrooms_ids[:,1] == 8, :]
print(bedroom_error)

# retire do bedroom_error o id do quarto
bedroom_error_id = bedroom_error[:, 0]
print(bedroom_error_id)

# crie um array com a informação completa de todas as linhas com o mesmo bedroom_error_id
beds_on_bedroom_error_id = bedrooms_ids[bedrooms_ids[:,0] == bedroom_error_id]
print(beds_on_bedroom_error_id)

# crie o id_1000015 array com as linhas completas dos quartos com este id
id_1000015 = bedrooms_ids[bedrooms_ids[:,0] == 1000015]
print(id_1000015)

# crie um array com os indices das linhas com quartos com este id
row_indices = np.where(bedrooms_ids[:,0] == 1000015)

# crie um array que contenha informação apenas dos quartos presentes em row_indices
id_1000015_2 = bedrooms_ids[row_indices[0],:]
print(id_1000015_2)


[[1000003       8       0]]
[1000003]
[[1000003       0       8]
 [1000003       1       0]
 [1000003       8       0]
 [1000003       1       0]
 [1000003       0       4]]
[[1000015       0       7]
 [1000015       3       0]
 [1000015       2       0]
 [1000015       1       0]
 [1000015       0       8]
 [1000015       1       0]]
[[1000015       0       7]
 [1000015       3       0]
 [1000015       2       0]
 [1000015       1       0]
 [1000015       0       8]
 [1000015       1       0]]


In [ ]:
# quando um quarto tem camas, não tem beliches. Quando tem beliches, não tem camas.
# Vamos criar uma nova coluna única com estas duas variáveis.

# crie um array de 1D com o número de camas e o número de beliches
beds_and_bunks = np.where(bedrooms_ids[:,1] == 0, bedrooms_ids[:,2], bedrooms_ids[:,1])
print(beds_and_bunks)

# faça o print do shape do array beds_and_bunks e do array bedrooms_ids
print(beds_and_bunks.shape, bedrooms_ids.shape)

# para podermos juntar os arrays, os shapes têm de ser compatíveis

# faça o reshape do array beds_and_bunks
reshaped_beds_and_bunks = beds_and_bunks.reshape((beds_and_bunks.shape[0],1))

# faça a contatenação dos dois arrays considerando a nova coluna em último
concatenated_bedrooms_ids = np.concatenate((bedrooms_ids,reshaped_beds_and_bunks), axis = 1)
print(concatenated_bedrooms_ids)

# agora que temos o novo array, vamos eliminar a coluna dos beliches

# faça delete da coluna dos beliches na nova tabela concatenada
concatenated_bedrooms_ids_no_bunks = np.delete(concatenated_bedrooms_ids, 2, axis = 1)